#!/bin/bash
docker run \
    --runtime nvidia \
    --network host \
    -it \
    --rm \
    --memory 500M \
    --memory-swap 3G \
    -v $HOME:$HOME \
    -e PYTHONPATH=$PYTHONPATH \
    -e HOSTNAME=`hostname` \
    -p 8888:8888 \
    --user jetson \
    --volume /tmp:/tmp \
    eml-lab python3
